version: "3.9"

services:
  base:
    build:
      args: &build-args
        NODEVS: $NODEVS
        PHPVS: $PHPVS
        X_ARCH: $X_ARCH
      target: base
    image: $ORG/php-$PHPVS:base-$TS-$X_ARCH
    platform: linux/$X_ARCH

  dumper:
    build:
      args: *build-args
      target: dumper
    depends_on: [base]
    image: $ORG/php-$PHPVS:dumper-$TS-$X_ARCH
    platform: linux/$X_ARCH

  cloud-cli:
    build:
      args: *build-args
      target: cloud-cli
    depends_on: [base]
    image: $ORG/php-$PHPVS:cloud-cli-$TS-$X_ARCH
    platform: linux/$X_ARCH

  qa:
    build:
      args: *build-args
      target: qa
    command: [bash]
    depends_on: [base]
    image: $ORG/php-$PHPVS:qa-$TS-$X_ARCH
    platform: linux/$X_ARCH

  fs:
    build:
      args: *build-args
      target: fs
    command: [bash]
    depends_on: [qa]
    image: $ORG/php-$PHPVS:fs-$TS-$X_ARCH
    platform: linux/$X_ARCH
