version: "3.9"

services:
  base:
    build:
      args: &build-args
        NODEVS: ${NODEVS:-18}
        PHPVS: ${PHPVS:-8.2}
        X_ARCH: $X_ARCH
      target: base
    env_file: .env
    image: $ORG/php-$PHPVS:base-$TS-$X_ARCH
    labels: &labels
      maintainer: Mihai Stancu <mihai.stancu@neurony.ro>
    platform: linux/$X_ARCH

  qa:
    build:
      args: *build-args
      target: qa
    command: [bash]
    depends_on: [base]
    env_file: .env
    image: $ORG/php-$PHPVS:qa-$TS-$X_ARCH
    labels: *labels
    platform: linux/$X_ARCH

  fs:
    build:
      args: *build-args
      target: fs
    command: [bash]
    depends_on: [qa]
    env_file: .env
    image: $ORG/php-$PHPVS:fs-$TS-$X_ARCH
    labels: *labels
    platform: linux/$X_ARCH
