version: "3.9"

services:
  cli:
    build:
      target: cli
      args: &build-args
        BASE: ${BASE:-ubuntu:20.04}
        NODEVS: ${NODEVS:-16}
        PHPVS: ${PHPVS:-8.1}
        X_ARCH: ${X_ARCH:-amd64}
        X_UID: ${XID:-1000:1000}
    image: $ORG/php-${PHPVS}:cli-${TS:-latest}-${X_ARCH:-amd64}
    labels: &labels
      maintainer: Mihai Stancu <mihai.stancu@neurony.ro>
    platform: linux/${X_ARCH:-amd64}

  fpm:
    build:
      target: fpm
      args: *build-args
    depends_on: [cli]
    image: $ORG/php-${PHPVS}:fpm-${TS:-latest}-${X_ARCH:-amd64}
    labels: *labels
    platform: linux/${X_ARCH:-amd64}

  qa:
    build:
      target: qa
      args: *build-args
    depends_on: [fpm]
    image: $ORG/php-${PHPVS}:qa-${TS:-latest}-${X_ARCH:-amd64}
    labels: *labels
    platform: linux/${X_ARCH:-amd64}

  fs:
    build:
      target: fs
      args: *build-args
    depends_on: [qa]
    image: $ORG/php-${PHPVS}:fs-${TS:-latest}-${X_ARCH:-amd64}
    labels: *labels
    platform: linux/${X_ARCH:-amd64}

  dev:
    build:
      target: dev
      args: *build-args
    depends_on: [fs]
    image: $ORG/php-${PHPVS}:dev-${TS:-latest}-${X_ARCH:-amd64}
    labels: *labels
    platform: linux/${X_ARCH:-amd64}
    ports: [ 80:80, 443:443, 9000:9000, 9912:9912 ]
