#!/bin/bash

### BEGIN INIT PHP-FPM
# Provides:          php-fpm
# Short-Description: PHP Fast Process Manager
# Description:       A shortcut to the first available PHP-FPM server configuration installed.
### END INIT PHP-FPM

SERVICE=$(ls /etc/init.d/php?.?-fpm | head -1);

[[ ! -z "$SERVICE" ]] && source $SERVICE || exit 1;
